name: Empaquetamiento
on: [push]
jobs:
  prueba:
    name: prueba de comando
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - run: mkdir Inventarios-zip
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r -vl ./Inventarios-zip/Inventarios.zip ./Inventarios
